name: Conditional Execution Statements

on: [workflow_dispatch, pull_request]


jobs:
    my-job1:
        if: ${{vars.value == 1}}
        runs-on: ubuntu-latest
        steps:
            - run: echo "executing job1"

            - name: step to run for num value 1
              if: ${{vars.num == 1}}
              run: echo "The num value is 1"

            - name: step to run for num value 2
              if: ${{vars.num == 2}}
              run: echo "The num value is 2"

            - name: env step
              if: ${{env.flag == 'yes'}}
              run: echo "the flag is yes"
              env:
                flag: "yes"
            

            

    my-job2:
        if: ${{vars.value == 2}}
        runs-on: ubuntu-latest
        steps:
            - run: echo "executing job2"


    my-job3:
        runs-on: ubuntu-latest
        steps:
            - name: if_issue
              if: github.event.issue
              run: echo "this is triggered due to an issue"

            - name: if_pr
              if: github.event.pull_request
              run: echo "This is triggered due to an pull request"

    

