name: Conditional Execution Statements

on: workflow_dispatch


jobs:
    my-job1:
        if: ${{vars.value == 1}}
        runs-on: ubuntu-latest
        steps:
            - run: echo "executing job1"

    my-job2:
        if: ${{vars.value == 2}}
        runs-on: ubuntu-latest
        steps:
            - run: echo "executing job2"

    

