name: Secrets and environment Variables

on: [push]

env:
    level: 'Workflow level'

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: echo 'This is triggered by push event'

            # Use the variables
            - name: Using Variables
              run: echo '${{vars.GREETING}} User'

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: Using Secrets
              run: echo 'secret value is ${{secrets.MY_SECRET}}'

            - name: Using Environment Variables
              run: echo 'Secret is set as Environment variable'
              env:
                MY_SECRET: ${{secrets.MY_SECRET}}

            - name: Using workflow Environment variables
              run: echo 'The value of variable level is ${{env.level}}'


    job3:
        runs-on: ubuntu-latest
        env:
            level: 'Job level'

        steps:
            - name: Checking Job level environment variable
              run: |
               echo 'The value of level here is $level'
               echo "The value of level here is $level"
               echo 'The value of level here is ${{env.level}}'

            - name: Checking Step level environment variable
              run: echo 'The value of level here is ${{env.level}}'
              env:
                level: 'Step level'

