name: Show Results

on:
  workflow_dispatch: 

jobs:
  upload-results:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Upload the results.html file as an artifact
      - name: Upload results.html
        uses: actions/upload-artifact@v4
        with:
          name: results.html
          path: results.html
