name: Show Results

on:
  workflow_dispatch: 

jobs:
  upload-results:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Upload the results.html file as an artifact
      - name: Upload results.html
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: results.html
